[package]
name = "ratex-pdf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "PDF export for RaTeX DisplayList using pdf-writer"

[dependencies]
ratex-types = { workspace = true }
ratex-font  = { workspace = true }
ratex-font-loader = { workspace = true, features = ["embed-fonts"] }
pdf-writer  = "0.14"
subsetter   = "0.2"
skrifa      = "0.42"
ab_glyph    = "0.2"
miniz_oxide = "0.9"
ratex-unicode-font = { workspace = true }

ratex-layout      = { workspace = true, optional = true }
ratex-parser      = { workspace = true, optional = true }

[features]
default = []
cli = ["dep:ratex-layout", "dep:ratex-parser"]

[[bin]]
name = "render-pdf"
path = "src/bin/render_pdf.rs"
required-features = ["cli"]

[dev-dependencies]
ratex-layout = { workspace = true }
ratex-parser = { workspace = true }
